### ISSUE TITLE
much worse assembly N50 in new version of wtdbg2

### ISSUE THREAD

**Issue by ishengtsai** [ruanjue/wtdbg2#47] opened 2018-11-23 06:32 UTC
Hi,

I have around 30X of an 1.5Gb insect genome. When trying to reassemble using the latest version I have much worse N50 and bigger genome. I was wondering if anyone can comment on the parameters that I should tweak please? Thanks.

Version: 1.1.006
Assembly Size 1.671Gb
N50 3Mb
Largest contig 16.1Mb

Version 2.2
Assembly Size 2.237Gb
N50 132kb
Largest contig 1.8Mb

parameters:  -p19 -AS2 -e2 in both cases.

**Comment by ruanjue** [comment] 2018-11-23 09:09
What kind of sequencing techonology did you use?

**Comment by ishengtsai** [comment] 2018-11-23 09:17
Sorry! I forgot to mention. Nanopore 1D reads.

**Comment by ruanjue** [comment] 2018-11-23 09:40
Could you send the log file of wtdbg2.2 to my email ruanjue AT gmail.com

**Comment by ruanjue** [comment] 2018-11-26 01:16
Thanks for suggestions.

There were three major differences between two runs, wtdbg-2.1 and wtdbg-2.2. 

1) '-K 1000' in 2.1, while '-K 23368' in 2.2. It was caused by wtdbg2.2 set default cutoff to ">= 1000 and >= (1 - 0.05)". It is really a problem, I will try to find a good way to set the cutoff. Now, please set '-K 1000.0'.

2) 2.1 used 9,118,484 data, while 2.2 used 7,094,607 reads. You had input the same filenames. Let's check what wrong with it.

3) 2.2 will delete multiple alignments between two reads, while 2.1 won't. I will provide a option to control it.

Best,
Jue

**Comment by ishengtsai** [comment] 2018-11-26 01:32
Many thanks. 

Just checked - there were a total of 9,118,419 reads, so I suspect the slightly higher number of reads in 2.1 was due to splitting of ultra long reads, while 2.2 really excluded a lot of shorter reads?

Does option 3 make the assembly quicker but less contiguated?

**Comment by ruanjue** [comment] 2018-11-26 01:37
2) the total basepairs differed much, 2.1 took 79 Gb, 2.2 took 62 Gb. Could you have a try on one or two input files? I am not sure why the total bases differed.

3) Not quicker, but bring more continguity in my tests.

**Comment by ishengtsai** [comment] 2018-11-26 01:53
2. There were a total of 10 fastq files, do you mean to let me try using one merged fastq file?

3. So to test this option, I would set -K 1000.0 and rerun v2.2?

**Comment by ruanjue** [comment] 2018-11-26 01:55
2) No merged, but one or two of them, to see the difference.

3) I haven't updated it on GitHub.

**Closed** 2018-12-03 05:46 UTC
